name: Laravel CI/CD

on:
  push:
    branches:
      - master # Cambia "main" por la rama que usas para producción

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.1 # Cambia según tu versión de PHP
        extensions: mbstring, bcmath, pdo, mysql
        tools: composer

    # - name: Install dependencies
    #   run: composer install --no-dev --optimize-autoloader

    # - name: Run Laravel tests
    #   run: php artisan test

    - name: Deploy to AWS EC2
      env:
        AWS_HOST: ${{ secrets.AWS_HOST }}
        AWS_USER: ${{ secrets.AWS_USER }}
        SSH_KEY: ${{ secrets.SSH_KEY }}
      run: |
        echo "$SSH_KEY" > ssh_key.pem
        chmod 600 ssh_key.pem
        ssh -o StrictHostKeyChecking=no -i ssh_key.pem $AWS_USER@$AWS_HOST << 'EOF'
          cd /var/www/laravel
          git pull origin main
          composer install --no-dev --optimize-autoloader
          php artisan migrate --force
          php artisan cache:clear
          php artisan config:cache
          php artisan route:cache
        EOF

